# -*- coding: utf-8 -*-
"""Data_Science_Master_FinalProject_mcLog.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IUdWHYHWoxhNObUTJvh4inn68ogMNFFi
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

df=pd.read_csv('/content/molecule_data_modified - Melting Point.csv')

df=df.dropna()

df.head()
df.info()
df.describe()

df_clean = df.drop(columns=["name", "smiles","mw_normalized","TPSA_normalized"])

X = df_clean.drop(columns=["mpC"])
y = df_clean["mpC"]

C = abs(y.min()) + 1
y_log = np.log(y + C)

print("Shift constant C:", C)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

corr = pd.DataFrame(X_scaled, columns=X.columns).corr()

plt.figure(figsize=(12,8))
sns.heatmap(corr, cmap="coolwarm")
plt.title("Feature Correlation Matrix")
plt.show()

pca = PCA(n_components=0.95)
X_pca = pca.fit_transform(X_scaled)

print("Original features:", X.shape[1])
print("PCA features:", X_pca.shape[1])

X_train, X_test, y_train, y_test = train_test_split(
    X_pca, y_log, test_size=0.2, random_state=42
)

rf = RandomForestRegressor(
    n_estimators=100,
    max_depth=20,
    min_samples_leaf=2,
    min_samples_split=5,
    random_state=42
)

rf.fit(X_train, y_train)

y_pred_log = rf.predict(X_test)

y_pred = np.exp(y_pred_log) - C
y_test_original = np.exp(y_test) - C

rmse = np.sqrt(mean_squared_error(y_test_original, y_pred))
r2 = r2_score(y_test_original, y_pred)

print("RMSE:", rmse)
print("R2 Score:", r2)

plt.scatter(y_test_original, y_pred)
plt.plot(
    [y_test_original.min(), y_test_original.max()],
    [y_test_original.min(), y_test_original.max()],
    linestyle="--"
)
plt.xlabel("Actual mpC")
plt.ylabel("Predicted mpC")
plt.title("Predicted vs Actual mpC (Log Target)")
plt.show()