# -*- coding: utf-8 -*-
"""Data_Science_Master_FinalProject_SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12sTeyKlwi9iSztxp_pnzLbRUd-br_WDs
"""

from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

df=pd.read_csv('/content/molecule_data_modified - Melting Point.csv')

df=df.dropna()

df.head()
df.info()
df.describe()

df_clean = df.drop(columns=["name", "smiles","mw_normalized","TPSA_normalized"])

X = df_clean.drop(columns=["mpC"])
y = df_clean["mpC"]

C = abs(y.min()) + 1
y_log = np.log(y + C)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=0.95)
X_pca = pca.fit_transform(X_scaled)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_pca, y_log, test_size=0.2, random_state=42
)

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred_log_lr = lr.predict(X_test)

y_pred_lr = np.exp(y_pred_log_lr) - C
y_test_original = np.exp(y_test) - C

rmse_lr = np.sqrt(mean_squared_error(y_test_original, y_pred_lr))
r2_lr = r2_score(y_test_original, y_pred_lr)

print("Linear Regression RMSE:", rmse_lr)
print("Linear Regression R2:", r2_lr)

svr = SVR(
    kernel="rbf",
    C=10,
    gamma="scale",
    epsilon=0.1
)

svr.fit(X_train, y_train)

y_pred_log_svr = svr.predict(X_test)

y_pred_svr = np.exp(y_pred_log_svr) - C

rmse_svr = np.sqrt(mean_squared_error(y_test_original, y_pred_svr))
r2_svr = r2_score(y_test_original, y_pred_svr)

print("SVR RMSE:", rmse_svr)
print("SVR R2:", r2_svr)