# -*- coding: utf-8 -*-
"""Data_Science_Master_FinalProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E7bhEK6i1EB-rs6vJ8k-P6qL9fP1P-GC
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/molecule_data_modified - Melting Point.csv')

df.head()

df.info()

df=df.dropna()

df.info()

df.describe()

df_clean = df.drop(columns=["name", "smiles","mw_normalized","TPSA_normalized"])

X = df_clean.drop(columns=["mpC"])
y = df_clean["mpC"]

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

import seaborn as sns
import matplotlib.pyplot as plt

corr_matrix = pd.DataFrame(X_scaled, columns=X.columns).corr()

plt.figure(figsize=(12,8))
sns.heatmap(corr_matrix, cmap="coolwarm", annot=False)
plt.title("Feature Correlation Matrix")
plt.show()

from sklearn.decomposition import PCA

pca = PCA(n_components=0.95)  # keep 95% variance
X_pca = pca.fit_transform(X_scaled)

print("Original features:", X.shape[1])
print("Reduced features:", X_pca.shape[1])

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_pca, y, test_size=0.2, random_state=42
)

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train, y_train)

from sklearn.metrics import mean_squared_error, r2_score

y_pred = rf.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

"""# Task
Train a Linear Regression model on the preprocessed training data (X_train, y_train) and evaluate its performance on the test data (X_test, y_test) by calculating and printing the Mean Squared Error (MSE), Root Mean Squared Error (RMSE), and R2 Score. Finally, provide a summary of the Linear Regression model's performance based on these metrics.

## Train Linear Regression Model

### Subtask:
Train a Linear Regression model on the preprocessed training data (X_train, y_train).

**Reasoning**:
To train a Linear Regression model, I will first import the necessary class, instantiate the model, and then fit it to the training data (X_train, y_train).
"""

from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

print("Linear Regression model trained successfully.")