# -*- coding: utf-8 -*-
"""DscProDecisionANN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11knzEClve7_GroSgO_9opt4ilqpmtBp7
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/df4.csv')

df.head()

df.columns

features = [
    'COUNT(I.INT_SEQ_NO)',
    'SUM(I.INT_PAYABLE_AMT)',
    'INT_SUM_INSURED',
    'ANNUAL_TOTAL_PREMIUM',
    'Duration',
    'PAY_CAT_DESC',
    'CUS_INDV_TITLE'
]

X = df[features]
y = df['blackList_status']

X = X.fillna(0)

X = pd.get_dummies(
    X,
    columns=['PAY_CAT_DESC', 'CUS_INDV_TITLE'],
    drop_first=True
)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

"""Essential for ANN. All Numerical attributes"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam

model = Sequential()

model.add(Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)))
model.add(Dropout(0.3))

model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(1, activation='sigmoid'))  # Binary classification

model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train_scaled,
    y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

loss, accuracy = model.evaluate(X_test_scaled, y_test)
print("Test Accuracy:", accuracy)

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))

# Accuracy
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Train')
plt.plot(history.history['val_accuracy'], label='Validation')
plt.title('ANN Accuracy')
plt.legend()

# Loss
plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Train')
plt.plot(history.history['val_loss'], label='Validation')
plt.title('ANN Loss')
plt.legend()

plt.show()