# -*- coding: utf-8 -*-
"""DscProDecisionSVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gjla41NXg7XZfnx5PAp8blnLUsKvs8tS
"""

import pandas as pd

df=pd.read_csv('/content/researchdata.csv')

df.info()

df = df.fillna(0)

df.describe()

features = [
    'COUNT(I.INT_SEQ_NO)',
    'SUM(I.INT_PAYABLE_AMT)',
    'INT_SUM_INSURED',
    'ANNUAL_TOTAL_PREMIUM',
    'Duration',
    'PAY_CAT_DESC_ENC',
    'CUS_INDV_TITLE_ENC'
]

X = df[features]
y = df['blackList_status']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.svm import SVC

svm_model = SVC(
    kernel='rbf',
    C=1.0,
    gamma='scale',
    probability=True,
    random_state=42
)

svm_model.fit(X_train_scaled, y_train)

y_pred = svm_model.predict(X_test_scaled)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

y_prob = svm_model.predict_proba(X_test_scaled)[:, 1]

fpr, tpr, _ = roc_curve(y_test, y_prob)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(7,5))
plt.plot(fpr, tpr, label=f'AUC = {roc_auc:.2f}')
plt.plot([0,1], [0,1], linestyle='--')

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve - SVM')
plt.legend()
plt.grid(True)
plt.show()