# -*- coding: utf-8 -*-
"""DscProDecisionTree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZgqkNkYspWBRHSXtzx9FbaU-JSa2VUtr
"""

import pandas as pd

df1=pd.read_csv('/content/blacklist_md.csv')
df2=pd.read_csv('/content/non_blacklist_md.csv')

df1.head()

df2.head()

merged_df = pd.concat([df1, df2], ignore_index=True)
df3 = merged_df.sample(frac=1, random_state=42).reset_index(drop=True)
df3

df3['INT_DATE_LOSS'] = pd.to_datetime(df3['INT_DATE_LOSS'], format='%d-%b-%y', errors='coerce')
df3['INT_PERIOD_TO'] = pd.to_datetime(df3['INT_PERIOD_TO'], format='%d-%b-%y', errors='coerce')

df3['Duration'] = (df3['INT_PERIOD_TO'] - df3['INT_DATE_LOSS']).dt.days
df3

df3

df3['Duration'] = df3['Duration'].dt.days
display(df3.head())

"""Best for the decision tree, further no need to normalize. Just keep as it is"""

from sklearn.preprocessing import LabelEncoder

le_pay = LabelEncoder()
le_title = LabelEncoder()

df3['PAY_CAT_DESC_ENC'] = le_pay.fit_transform(df3['PAY_CAT_DESC'])
df3['CUS_INDV_TITLE_ENC'] = le_title.fit_transform(df3['CUS_INDV_TITLE'])

df3.drop(['PAY_CAT_DESC', 'CUS_INDV_TITLE'], axis=1, inplace=True)

df3

df3.info()

df3.describe()

features = [
    'COUNT(I.INT_SEQ_NO)',
    'SUM(I.INT_PAYABLE_AMT)',
    'INT_SUM_INSURED',
    'ANNUAL_TOTAL_PREMIUM',
    'Duration',
    'PAY_CAT_DESC_ENC',
    'CUS_INDV_TITLE_ENC'
]

X = df3[features]
y = df3['blackList_status']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(
    criterion='gini',      # or 'entropy'
    max_depth=5,           # prevents overfitting
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42
)

dt_model.fit(X_train, y_train)

y_pred = dt_model.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

import pandas as pd

feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': dt_model.feature_importances_
}).sort_values(by='Importance', ascending=False)

print(feature_importance)

# to visualize tree
import matplotlib.pyplot as plt
from sklearn.tree import plot_tree

plt.figure(figsize=(22, 12))

plot_tree(
    dt_model,
    feature_names=X.columns,
    class_names=['Not Blacklisted', 'Blacklisted'],
    filled=True,
    rounded=True,
    fontsize=10
)

plt.title("Decision Tree for Insurance Blacklist Prediction")
plt.show()
