# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DOL9XSUL3axqwTHnsSaHB-kZa9pRkJXl
"""

import pandas as pd
import numpy as np

df=pd.read_excel('/content/BradleyMeltingPointDataset.xlsx')

df

df.columns

df.drop(['key','csid', 'link', 'source', 'donotuse',
       'donotusebecause'],axis=1,inplace=True)

df

pip install rdkit

from rdkit import Chem
from rdkit.Chem import Descriptors

df['mw']=[Descriptors.MolWt(Chem.MolFromSmiles(x)) for x in df['smiles'] if Chem.MolFromSmiles(x) ]

df

df['bonds']=[mol.GetNumBonds(Chem.MolFromSmiles(x)) if Chem.MolFromSmiles(x) else None for x in df['smiles']]

from rdkit.Chem import rdMolDescriptors
df['numofrings']=[ rdMolDescriptors.CalcNumRings(Chem.MolFromSmiles(x)) if Chem.MolFromSmiles(x) else None for x in df['smiles']]

df['aromaticsrings']=[ rdMolDescriptors.CalcNumAromaticRings(Chem.MolFromSmiles(x)) if Chem.MolFromSmiles(x) else None for x in df['smiles']]

df['structuralcomplexcity']=[ Descriptors.Chi0(Chem.MolFromSmiles(x)) if Chem.MolFromSmiles(x) else None for x in df['smiles']]

df

df['double_bonds'] = [sum(1 for b in Chem.MolFromSmiles(x).GetBonds() if b.GetBondType()==Chem.rdchem.BondType.DOUBLE) if Chem.MolFromSmiles(x) else None for x in df['smiles']]
df['triple_bonds'] = [sum(1 for b in Chem.MolFromSmiles(x).GetBonds() if b.GetBondType()==Chem.rdchem.BondType.TRIPLE) if Chem.MolFromSmiles(x) else None for x in df['smiles']]

df

df['singlebonds']=df['bonds']-(df['double_bonds']+df['triple_bonds'])

df['aliphaticrings']=df['numofrings']-df['aromaticsrings']

df

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

# Fit and transform only the 'mw' column
df['mw_normalized'] = scaler.fit_transform(df[['mw']])

df['TPSA'] = [rdMolDescriptors.CalcTPSA(Chem.MolFromSmiles(x)) if Chem.MolFromSmiles(x) else None for x in df['smiles']]
df['HBD'] = [rdMolDescriptors.CalcNumHBD(Chem.MolFromSmiles(x)) if Chem.MolFromSmiles(x) else None for x in df['smiles']]
df['HBA'] = [rdMolDescriptors.CalcNumHBA(Chem.MolFromSmiles(x)) if Chem.MolFromSmiles(x) else None for x in df['smiles']]

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

features = ['mw', 'aromaticsrings',
            'structuralcomplexcity', 'double_bonds', 'triple_bonds',
            'singlebonds', 'aliphaticrings','TPSA']

target = 'mpC'

X = df[features]
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#train the model
model = RandomForestRegressor(
    n_estimators=200,      # number of trees
    max_depth=10,          # limit tree depth (prevent overfitting)
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error: {mae:.2f}")
print(f"R² Score: {r2:.3f}")

df.to_csv('molecule_data.csv', index=False)